### DISCUSSION TITLE
Why is my sync hook called at a high rate?

### DISCUSSION THREAD

**Discussion by NiklasRosenstein** [metacontroller/metacontroller#1055] [Q&A] [answered]
Hello 👋 I have a question about the frequency at which the sync hook is called. From what I can read in the documentation, it seems that the `resyncPeriodSeconds` usually dictates that frequency, unless the `resyncAfterSeconds` field in the sync response is set to a non-zero value.

However, my sync hook is called very frequently, like three times a second. There is only a single parent resource in the cluster for which it is being called. I do return `{"resyncAfterSeconds": 0}`, which according to the docs and the code means it is not scheduled any additional times:

https://github.com/metacontroller/metacontroller/blob/66c3b9788462ac4ff8a1ca1a07f2ab842311251e/pkg/controller/composite/controller_revision.go#L234-L239

https://github.com/metacontroller/metacontroller/blob/66c3b9788462ac4ff8a1ca1a07f2ab842311251e/pkg/controller/decorator/controller.go#L590-L592

Request logs from my composite controller webhook:

![image](https://github.com/user-attachments/assets/03d0afee-fad4-4db1-8c6f-ebf5bb5ed283)

This even happens when it returns no children. It stops when I remove the only parent object. I'm sure I've also observed this with a decorator controller before.

```yaml
kind: CompositeController
metadata:
  labels:
    app.kubernetes.io/instance: applicationmapper
    app.kubernetes.io/name: applicationmapper
    app.kubernetes.io/version: develop
  name: applicationmappers.niklasrosenstein.com
spec:
  childResources:
  - apiVersion: v1
    resource: namespaces
    updateStrategy:
      method: InPlace
  - apiVersion: v1
    resource: secrets
    updateStrategy:
      method: InPlace
  - apiVersion: v1
    resource: configmaps
    updateStrategy:
      method: InPlace
  - apiVersion: argoproj.io/v1alpha1
    resource: applications
    updateStrategy:
      method: InPlace
  generateSelector: true
  hooks:
    customize:
      version: v1
      webhook:
        timeout: 60s
        url: http://applicationmapper.applicationmapper/customize
    sync:
      version: v1
      webhook:
        timeout: 60s
        url: http://applicationmapper.applicationmapper/sync
  parentResource:
    apiVersion: niklasrosenstein.com/v1alpha1
    resource: applicationmappers
  resyncPeriodSeconds: 15
```

Using metacontroller v4.11.22

**Comment by newtondev** [comment]
Hi @NiklasRosenstein , thanks for report this issue. I will see if I can replicate this issue. Is it possible for you to share the webhook logic you are using, or even just the example response from the sync hook. Thanks

**Reply by NiklasRosenstein** [reply]
Sure! You should be able to replicate it by installing the Helm chart in this repository: https://github.com/NiklasRosenstein/k8s-applicationmapper/tree/0.2.0

Then deploy a resource that acts as a parent. A stripped down example:

```yaml
---
apiVersion: niklasrosenstein.com/v1alpha1
kind: ApplicationMapper
metadata:
  name: guestbooks
spec:
  inputQueries:
    - name: subscriptions
      static:
        - subscriptionId: customer-abc
        - subscriptionId: customer-xyz
        - subscriptionId: customer-opq
  helmTemplate: |
    {{- range $sub := .Values.subscriptions }}
    ---
    apiVersion: v1
    kind: Secret
    metadata:
      name: {{ $.Release.Name }}-{{ $sub.subscriptionId }}
      namespace: default
    stringData:
      SUBSCRIPTION_ID: {{ $sub.subscriptionId }}
    {{- end }}
```


![image](https://github.com/user-attachments/assets/162b6c9a-d13c-4fe6-a19f-6bd6415733b2)
