### DISCUSSION TITLE
Question: Taint node with decorate controller

### DISCUSSION THREAD

**Discussion by dumplinginsoda** [metacontroller/metacontroller#338] [Q&A] [answered]
Hi, I am trying to use decorator controllers to achieve node tainting. But sync request have `{'Node.v1': {}}` under attachment.
I was expecting actual existing nodes information.

Below is the spec section of my controller yaml:
```
spec:
  resources:
  - apiVersion: example.com/v1
     resource: nodetaints
  attachments:
  - apiVersion: v1
     resource: Nodes
  hooks:
    sync:
      webhook:
        url: example.svc/sync
```

Can you help me and see if there's something off with my spec? Or is retrieving node as attachment prohibited for some reason?
