### DISCUSSION TITLE
Introducing API changes to sync/customize/finalize hooks

### DISCUSSION THREAD

**Discussion by grzesuav** [metacontroller/metacontroller#370] [Ideas] [answered]
# Problem
Metacontroller have, besides CRD on which it base - `CompositeController` and `DecoratorController` also additional API contract on request/response on webhooks :
*  `sync`
* `finalize`
* `customize`

For now, `customize` hooks seems failry universal, but as part of it, `request` in `sync`/`finalize` is also dependant. I.e. part of `request` is `related` flat object map - https://metacontroller.github.io/metacontroller/api/compositecontroller.html#sync-hook-request. Recently I encounter an issue in which I would like to change the format of this map, but, as it is a part of API, it would be a breaking change. Ideally, we would propose a way of api versioning, which would make possible to gradually migrate customer operators in that scenario

**Comment by grzesuav** [comment]
cc: @AmitKumarDas

**Comment by AmitKumarDas** [comment]
@grzesuav Can you put some sample yaml etc of current request & response & how the future request & response look like.
In addition, what do you think about the `kind: ConversionReview`. Can it provide us with some reference ideas.

refer - https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#request (need to scroll down to check the request & response yamls)

**Reply by grzesuav** [reply]
I do not think it is related, I mean this mechanism is ment to be used to convert CRD's between versions. In our case, let's focus on `sync` hook - specifically `related` part :
```yaml
{
  "related": {
    "Pod.v1": {
        "someResource": {}
    }
  }
}
```
recently, when I wanted to extend this (due to https://github.com/metacontroller/metacontroller/issues/345) I unintentionally would introduce API breaking change , i.e. the request would look like -
```yaml
{
  "related": {
    "Pod.v1": {
        "someNamespace/someResource": {}
    }
  }
}
```
(so `namespace` part prepended to object name) - the main concer is it would cause all user controller to fail once it would be introduced.

**Reply by grzesuav** [reply]
this is just an example, focused on recent issue I have working on, but in reality currently format of `sync/finalize/customize` is fixed, so without any versioning we are glued to it

**Reply by grzesuav** [reply]
one of ideas is to extend the definition there, i.e. 
```yaml
---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: catset-controller
spec:
  parentResource:
   ...
  childResources:
  - apiVersion: v1
   ...
  hooks:
    sync:
      webhook:
        url: http://catset-controller.metacontroller/sync
    finalize:
      webhook:
        url: http://catset-controller.metacontroller/sync
---
```
to include versions 
```yaml
---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: catset-controller
spec:
  parentResource:
   ...
  childResources:
  - apiVersion: v1
   ...
  hooks:
    sync:
      v1:
        webhook:
          url: http://catset-controller.metacontroller/sync
    finalize:
      v1:
        webhook:
          url: http://catset-controller.metacontroller/sync
```


and defining versioned scheme of request/response. In that case :
* only one version can be present (either `v1` or any other)
* metacontroller will serialize request/response acordingly
* API deprecation policy will be set, to not have to deal with multiple versions, but also allow users to upgrade metacontroller and then gradually migrate controller to new version

I am usnure how complicated it would be to handle this in code, hopefully if code will be structured and abstracted it won't be so painfull. But huge adventage will be that user can upgrade metacontroller, and then adjust their controller to new API.


P.S. what you posted (conversion webhook) will be good to update CRD, (i.e. default `sync` to `sync/v1` etc).

**Reply by AmitKumarDas** [reply]
@grzesuav I was trying to solve the problem by limiting the solution to the hook's request & response. The reference that I had provided earlier was actually to think on those lines.

IMO we may want to avoid CRD schema changes as much as possible to handle current problem. For example below will mandate a new CRD versioning. This in turn couples metacontroller based webhook deployments to adhere to Kubernetes paradigms. 
```yaml
spec:
  finalize:
    v1:
      webhook:
        url: http://catset-controller.metacontroller/sync
``` 

Can metacontroller deal with this problem by introducing version & other fields (e.q. request id, & more) inside the HookRequest & HookResponse structures? This will let Metacontroller to support multiple webhook implementations simultaneously & more importantly be decoupled from Kubernetes CRDs. This has in-fact been the best thing so far i.e. Metacontroller's internal logic is not tied to Kubernetes workflow.

**Reply by sathieu** [reply]
@grzesuav What about moving the version under `webhook`?

```yaml
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: catset-controller
spec:
  parentResource:
   ...
  childResources:
  - apiVersion: v1
   ...
  hooks:
    sync:
      webhook:
        url: http://catset-controller.metacontroller/sync
    finalize:
      webhook:
        url: http://catset-controller.metacontroller/sync
        version: v1 # <<< HERE
```
