### ISSUE TITLE
Option to Ignore unknown child resources

### ISSUE THREAD

**Issue by ikreymer** [metacontroller/metacontroller#1008]
It would be useful if unknown child CRDs could be ignored optionally. For example, a controller might control Vertical Pod Autoscalers, but only if VPA is installed. It would be helpful to be able to specify:
```
  - apiVersion: autoscaling.k8s.io/v1
    resource: verticalpodautoscalers
    updateStrategy:
      method: OnDelete
    optional: true
```
and have metacontroller sync ignore these child resources if they don't exist.
Currently, it errors with `discovery: can't find resource verticalpodautoscalers in apiVersion autoscaling.k8s.io/v1"`

It should also ignore these children if they are provided, though it is up to the implementor to determine if the CRDs are installed.
