### ISSUE TITLE
Support distinct source & target k8s clusters/kubeconfigs to sync/decorate resources 

### ISSUE THREAD

**Issue by gberche-orange** [metacontroller/metacontroller#1019]
I need to an operator that can watch a source k8s cluster from kubeconfig1 and sync objects to a target cluster using kubeconfig2.

Specifically, this is useful to write vcluster plugins, see https://vcluster.com/docs/vcluster/configure/vcluster-yaml/plugins?x0=1
> A plugin in its purest form is a [Kubernetes operator](https://kubernetes.io/docs/concepts/extend-kubernetes/operator/) that has access to both the virtual cluster and the host cluster simultaneously. This is the main difference between a vCluster plugin and a regular Kubernetes operator that you would install inside the virtual cluster itself. Given this dual access, the plugin is able to translate resources between both clusters, which is the basic building block of how vCluster works.

According to https://metacontroller.github.io/metacontroller/guide/configuration.html metacontroller seems to currently only support a single kubeconfig
> Flag | Description
> -- | --
> --kubeconfig | Path to kubeconfig file (same format as used by kubectl); if not specified, use in-cluster config (e.g. --kubeconfig=/path/to/kubeconfig).
> 

The [DecoratorController](https://metacontroller.github.io/metacontroller/api/decoratorcontroller.html) seems then be a good fit to syncing/decorating resources between the source and the target cluster.

**Comment by grzesuav** [comment]
yes, metacontroller does not support multi-cluster pattern, and for foreseeable feature won't support that. 

There is not many multi-clusters frameworks in the are - like `kcp`, stuff done in https://github.com/kubernetes-sigs/cluster-api/blob/main/controllers/remote/cluster_cache_tracker.go or across various projects like ArgoCD etc. 

Recenty multi-cluster sig is working on cluster inventory -https://docs.google.com/document/d/1sUWbe81BTclQ4Uax3flnCoKtEWngH-JA9MyCqljJCBM/edit?tab=t.0#heading=h.6qhwtyz405ii - where remote cluster credentials could be defined. Unless there is more support in community for this I consider this feature blocked

**Comment by grzesuav** [comment]
recenly I see some development in this area  https://github.com/kubernetes-sigs/multicluster-runtime

**Comment by gberche-orange** [comment]
thanks for the heads up !

I see related example for a sync sync-local-to-remote at https://github.com/kubernetes-sigs/multicluster-runtime/blob/main/examples/sync-local-to-remote/README.md accepting a CSV list of remote kubeconfig
```
go run . \
    -local-kubeconfig ./cluster1.kubeconfig \
    -provider-kubeconfigs ./cluster1.kubeconfig,./cluster2.kubeconfig,./cluster3.kubeconfig
```

https://github.com/kubernetes-sigs/multicluster-runtime/blob/087d80cae466d81ea74669620412ab8373b2900d/examples/sync-local-to-remote/main.go#L140-L163

any idea of how the remote cluster(s) would be surfaced into the DecoratorController CRD ? 

For a single remote cluster, a new "remoteClusterName" key with the cluster name as value ? 

```yaml
apiVersion: metacontroller.k8s.io/v1alpha1
kind: DecoratorController
metadata:
  name: service-per-pod
spec:
  resources:
  - apiVersion: apps/v1
    resource: statefulsets
    annotationSelector:
      matchExpressions:
      - {key: service-per-pod-label, operator: Exists}
      - {key: service-per-pod-ports, operator: Exists}
  remoteClusterName: cluster1
  attachments:
  - apiVersion: v1
    resource: services
  hooks:
    sync:
      webhook:
        url: http://service-per-pod.metacontroller/sync-service-per-pod
        timeout: 10s
```
