### ISSUE TITLE
High CPU load for child matching

### ISSUE THREAD

**Issue by woehrl01** [metacontroller/metacontroller#1085]
Hi,

after SSR is merged, we can see that the next bottleneck is now the matching of children. In our case we have many cluster wide resources, so it needs to evaluate every available child on every change.

See the pprof:

<img width="1317" alt="Image" src="https://github.com/user-attachments/assets/51151d1e-08a0-4957-b305-9568fb3d36f2" />

I think the problem is that it matches every child on each run, I think it makes sense to keep the ownership and only match it once during child creation/removal, so that this in `syncParentObject` the `claimChildren` call is not executed at all.

I'm open to contribute a PR, but would like to discuss how to handle that issue, before diving in.

@grzesuav appreciate your ideas here, thanks!

**Comment by woehrl01** [comment]
The important thing to mention is that the parent is a cluster wide resource, because we have to manage some cluster wide resources with it (e.g. persistentvolumes, namespaces)

Here is the controller config:

```yaml
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: some-controller
spec:
  childResources:
  - apiVersion: networking.istio.io/v1beta1
    resource: serviceentries
    updateStrategy:
      method: InPlace
  - apiVersion: v1
    resource: namespaces
    updateStrategy:
      method: InPlace
  - apiVersion: v1
    resource: configmaps
    updateStrategy:
      method: InPlace
  - apiVersion: batch/v1
    resource: jobs
    updateStrategy:
      method: Recreate
  - apiVersion: batch/v1
    resource: cronjobs
    updateStrategy:
      method: InPlace
  - apiVersion: v1
    resource: persistentvolumes
    updateStrategy:
      method: InPlace
  - apiVersion: v1
    resource: persistentvolumeclaims
    updateStrategy:
      method: InPlace
  - apiVersion: autoscaling.k8s.io/v1
    resource: verticalpodautoscalers
    updateStrategy:
      method: InPlace
  - apiVersion: v1
    resource: services
    updateStrategy:
      method: InPlace
  - apiVersion: apps/v1
    resource: deployments
    updateStrategy:
      method: InPlace
  - apiVersion: apps/v1
    resource: statefulsets
    updateStrategy:
      method: InPlace
  - apiVersion: v1
    resource: serviceaccounts
    updateStrategy:
      method: InPlace
  - apiVersion: external-secrets.io/v1beta1
    resource: externalsecrets
    updateStrategy:
      method: InPlace
  - apiVersion: keda.sh/v1alpha1
    resource: scaledjobs
    updateStrategy:
      method: InPlace
  - apiVersion: keda.sh/v1alpha1
    resource: scaledobjects
    updateStrategy:
      method: InPlace
  - apiVersion: networking.istio.io/v1alpha3
    resource: envoyfilters
    updateStrategy:
      method: InPlace
  - apiVersion: networking.istio.io/v1beta1
    resource: gateways
    updateStrategy:
      method: InPlace
  - apiVersion: policy/v1
    resource: poddisruptionbudgets
    updateStrategy:
      method: InPlace
  - apiVersion: networking.istio.io/v1beta1
    resource: virtualservices
    updateStrategy:
      method: InPlace
  - apiVersion: networking.istio.io/v1beta1
    resource: destinationrules
    updateStrategy:
      method: InPlace
  hooks:
    customize:
      version: v1
      webhook:
        timeout: 60s
        url: http://some.namespace.svc.cluster.local/related-resources
    sync:
      version: v1
      webhook:
        timeout: 60s
        url: http://some.namespace.svc.cluster.local/sync
  parentResource:
    apiVersion: custom/v1
    resource: applications
    revisionHistory:
      fieldPaths:
      - spec
  resyncPeriodSeconds: 600
```
