### ISSUE TITLE
I cannot get istio gateways with the decorator controller 

### ISSUE THREAD

**Issue by rlewkowicz** [metacontroller/metacontroller#175]
```
apiVersion: metacontroller.k8s.io/v1alpha1
kind: DecoratorController
metadata:
  name: gateway-configmap-generator-controller
spec:
  resources:
  - apiVersion: networking.istio.io/v1beta1
    resource: gateways
  hooks:
    sync:
      webhook:
        url: http://gateway-configmap-generator-controller.metacontroller/sync
        timeout: 10s
  ```      
Will error:
```
E0201 14:53:00.360131       1 discovery.go:103] Failed to fetch discovery info: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
```

**Comment by rlewkowicz** [comment]
I'll even add this, I have a custom deployment that just logs info:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-configmap-generator-controller
  namespace: metacontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-configmap-generator-controller
  template:
    metadata:
      labels:
        app: gateway-configmap-generator-controller
    spec:
      containers:
      - name: controller
        image: "tiangolo/uvicorn-gunicorn-fastapi:latest"
        workingDir: /hooks
        command: ["uvicorn", "sync:app", "--reload"]
        volumeMounts:
        - name: hooks
          mountPath: /hooks
      volumes:
      - name: hooks
        configMap:
          name: gateway-configmap-generator-controller
     ```
     
    ```
$ cat sync.py
from typing import Optional
import logging
import typing

from fastapi import FastAPI, Request

logging.basicConfig(level=logging.DEBUG)
LOGGER = logging.getLogger(__name__)
LOGGER.info("started")

app = FastAPI()

@app.api_route("/{anything:path}", methods=["GET", "POST"])
async def catch_all(anything: str, request: Request):
    LOGGER.info({"Method": request.method,
            "URL": request.url,
            "Headers": dict(request.headers.items()),
            "Query Parameters": dict(request.query_params.items()),
            "Path Parameters": request.path_params,
            "Client": request.client.host,
            "Body": await request.body()})
  ```
  
  I can port forward to this, and hitting it with anything works, but metacontroller never hits it.
