### ISSUE TITLE
no matches for kind "DecoratorController" in version "metacontroller.k8s.io/v1alpha1"

### ISSUE THREAD

**Issue by mansing2** [metacontroller/metacontroller#188]
Hello,

I'm trying to setup Hazelcast external client using Metacontroller approach as described here, https://guides.hazelcast.org/kubernetes-external-client/ the deployment of metacontroller service account,  role/binding, CRDs for Metacontroller APIs, and the Metacontroller StatefulSet goes well.

But when I am trying to deploy another yaml manifests which make use of decoratorcontroller from the API version 'metacontroller.k8s.io/v1alpha1' getting failed with error "no matches for kind "DecoratorController" in version "metacontroller.k8s.io/v1alpha1" "

```
apiVersion: metacontroller.k8s.io/v1alpha1
kind: DecoratorController
metadata:
  name: service-per-pod
spec:
  resources:
  - apiVersion: apps/v1
    resource: statefulsets
    annotationSelector:
      matchExpressions:
      - {key: service-per-pod-label, operator: Exists}
      - {key: service-per-pod-ports, operator: Exists}
  attachments:
  - apiVersion: v1
    resource: services
  hooks:
    sync:
      webhook:
        url: http://service-per-pod.metacontroller/sync-service-per-pod

```
Any help is appreciated.
