### ISSUE TITLE
My update of mongodb_cr involves 3 statefulset cpu, but only one update sts, the strategy is to RollingInPlace

### ISSUE THREAD

**Issue by tengzhuofei** [metacontroller/metacontroller#261]
When I updated the mongodb_cr, the metacontroller did not update the statefulset of multiple children at the same time, but when I deleted all the controllerrevisions.metacontroller.k8s.io resource and re-updated the cpu, two more statefulsets were updated(mongodb-sharded-configsvr、mongodb-sharded-shard0-data).

operator Steps

shardsvr.dataNode.resources.requests.cpu= new value
shardsvr.arbiter.resources.requests.cpu= new value
configsvr.resources.requests.cpu= new value

kubectl apply -f mongodb-cr.yml

version

k8s v0.15.11  metacontroller 1.5.8

statefulset

mongodb-sharded-configsvr        1/1     2d20h
mongodb-sharded-shard0-arbiter   1/1     2d20h
mongodb-sharded-shard0-data      2/2     2d20h

```
mongodb-cr.yml
spec
  shardsvr:
    dataNode:
      resources:
        limits:
          cpu: "4"
          memory: "10Gi"
        requests:
          cpu: "0.5"
          memory: "0.5Gi"
    
      arbiter:
            replicas: 1
            outConfigEnable: false
            resources:
              limits:
                cpu: "4"
                memory: "4Gi"
              requests:
                cpu: "0.2"
                memory: "0.2Gi"
  configsvr:
    outConfigEnable: false
    resources:
      limits:
        cpu: "4"
        memory: "4Gi"
      requests:
        cpu: "0.4"
        memory: "0.4Gi"

## mongos节点信息 
  mongos:
    outConfigEnable: false
    resources:
      limits:
        cpu: "4"
        memory: "6Gi"
      requests:
        cpu: "0.3"
        memory: "0.3Gi"
```
controller.yml

```
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: mongodbcluster-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: icos.city/v1
    resource: mongodbclusters
  childResources:
    - apiVersion: v1
      resource: secrets
    - apiVersion: v1
      resource: pods
    - apiVersion: v1
      resource: services
    - apiVersion: v1
      resource: serviceaccounts
    - apiVersion: policy/v1beta1
      resource: poddisruptionbudgets
    - apiVersion: apps/v1
      resource: deployments
      updateStrategy:
        method: RollingInPlace
    - apiVersion: apps/v1
      resource: statefulsets
      updateStrategy:
        method: RollingInPlace

  hooks:
    sync:
      webhook:
        url: http://mongodbcluster-controller-operator.metacontroller/sync
    finalize:
      webhook:
        url: http://mongodbcluster-controller-operator.metacontroller/sync
    ```

**Comment by grzesuav** [comment]
hi @tengzhuofei , may I ask of formatting the `CompositeController` definition as:
```yaml
formatAsYaml:
- insteadOf: plaintex
  asItIs: easierToRead
```
as currently I cannot follow the config.

Also, can you elaborate :
- what is happening now
- what is expected
- attach event related to problematic resource (i.e. `kubectl describe Pod problematicPod`)
?

Thanks

**Comment by tengzhuofei** [comment]
![image](https://user-images.githubusercontent.com/49179198/118800819-e89a4780-b8d2-11eb-9228-b009658a7252.png)

**Comment by tengzhuofei** [comment]
> When I updated the mongodb_cr, the metacontroller did not update the statefulset of multiple children at the same time, but when I deleted all the controllerrevisions.metacontroller.k8s.io resource and re-updated the cpu, two more statefulsets were updated(mongodb-sharded-configsvr、mongodb-sharded-shard0-data).
> 
> operator Steps
> 
> shardsvr.dataNode.resources.requests.cpu= new value
> shardsvr.arbiter.resources.requests.cpu= new value
> configsvr.resources.requests.cpu= new value
> 
> kubectl apply -f mongodb-cr.yml
> 
> version
> 
> k8s v0.15.11 metacontroller 1.5.8
> 
> statefulset
> 
> mongodb-sharded-configsvr 1/1 2d20h
> mongodb-sharded-shard0-arbiter 1/1 2d20h
> mongodb-sharded-shard0-data 2/2 2d20h
> 
> ```
> mongodb-cr.yml
> spec
>   shardsvr:
>     dataNode:
>       resources:
>         limits:
>           cpu: "4"
>           memory: "10Gi"
>         requests:
>           cpu: "0.5"
>           memory: "0.5Gi"
>     
>       arbiter:
>             replicas: 1
>             outConfigEnable: false
>             resources:
>               limits:
>                 cpu: "4"
>                 memory: "4Gi"
>               requests:
>                 cpu: "0.2"
>                 memory: "0.2Gi"
>   configsvr:
>     outConfigEnable: false
>     resources:
>       limits:
>         cpu: "4"
>         memory: "4Gi"
>       requests:
>         cpu: "0.4"
>         memory: "0.4Gi"
> 
> ## mongos节点信息 
>   mongos:
>     outConfigEnable: false
>     resources:
>       limits:
>         cpu: "4"
>         memory: "6Gi"
>       requests:
>         cpu: "0.3"
>         memory: "0.3Gi"
> ```
> 
> controller.yml
> 
> ```
> apiVersion: metacontroller.k8s.io/v1alpha1
> kind: CompositeController
> metadata:
>   name: mongodbcluster-controller
> spec:
>   generateSelector: true
>   parentResource:
>     apiVersion: icos.city/v1
>     resource: mongodbclusters
>   childResources:
>     - apiVersion: v1
>       resource: secrets
>     - apiVersion: v1
>       resource: pods
>     - apiVersion: v1
>       resource: services
>     - apiVersion: v1
>       resource: serviceaccounts
>     - apiVersion: policy/v1beta1
>       resource: poddisruptionbudgets
>     - apiVersion: apps/v1
>       resource: deployments
>       updateStrategy:
>         method: RollingInPlace
>     - apiVersion: apps/v1
>       resource: statefulsets
>       updateStrategy:
>         method: RollingInPlace
> 
>   hooks:
>     sync:
>       webhook:
>         url: http://mongodbcluster-controller-operator.metacontroller/sync
>     finalize:
>       webhook:
>         url: http://mongodbcluster-controller-operator.metacontroller/sync
>     ```
> ```

**Comment by tengzhuofei** [comment]
k8s 1.19 ok

**Comment by grzesuav** [comment]
hi @tengzhuofei

do you see anything in the metacontroller logs ? Also, did the child `StatefulSet` has been updated and the change did not propagate to its pods ? You have boths
```yaml
    - apiVersion: v1
      resource: pods
    - apiVersion: apps/v1
      resource: deployments
      updateStrategy:
        method: RollingInPlace
    - apiVersion: apps/v1
      resource: statefulsets
      updateStrategy:
        method: RollingInPlace
```
so the pods which are not updated are direct children, or your children are `StatefulSets` ? Please notice that for `Pod` resources you did not declare any `updateStrategy`, so by default they use `OnDelete` - which means they won't get any update, unless explicitly deleted.
