### ISSUE TITLE
Customize hook response cached with only name and clashes between different namespaces

### ISSUE THREAD

**Issue by srfrnk** [metacontroller/metacontroller#414]
**EDIT**: Leaving the full conversation intact but after digging deeper the real issue can be found [here](https://github.com/metacontroller/metacontroller/issues/414#issuecomment-1014242000)

**Previous description:**
I'm getting a strange issue when trying to use `relatedResources` with two different namespaces.

I'm deploying these CRDs:
```yaml
apiVersion: jabos.io/v1
kind: GitRepository
metadata:
  name: first-repo
  namespace: stg
spec:
  url: https://github.com/srfrnk/jabos-examples.git
  branch: stg
---
apiVersion: jabos.io/v1
kind: JsonnetManifest
metadata:
  name: simple-jsonnet-manifest
  namespace: stg
spec:
  gitRepository: first-repo
  path: simple-runtime/manifests
  targetNamespace: stg
  commitTLAKey: latestCommitId
---
apiVersion: jabos.io/v1
kind: GitRepository
metadata:
  name: first-repo
  namespace: example-env
spec:
  url: https://github.com/srfrnk/jabos-examples.git
  branch: main
---
apiVersion: jabos.io/v1
kind: JsonnetManifest
metadata:
  name: simple-jsonnet-manifest
  namespace: example-env
spec:
  gitRepository: first-repo
  path: simple-runtime/manifests
  targetNamespace: example-env
  commitTLAKey: latestCommitId
---
```

`JsonnetManifest` is controlled by a `DecoratorController` whose `customize` hook returns:
```json
{"relatedResources":[{"apiVersion":"jabos.io/v1","resource":"git-repositories","namespace":"stg","names":["first-repo"]}]}
```
and
```json
{"relatedResources":[{"apiVersion":"jabos.io/v1","resource":"git-repositories","namespace":"example-env","names":["first-repo"]}]}
```
Respectively.

However the second CRD deployed (always the second) will show the following `Event` and fail to sync:
```bash
Warning  SyncError  2s (x11 over 7s)  metacontroller  Sync error: requested related object namespace stg differs from parent object namespace example-env
```

What's wrong here? Should the related object namespace not be just the parent namespace with this configuration?

**Comment by srfrnk** [comment]
Furthermore - after that happens when deleting the resource the delete will stall...
Logs seems to indicate that the `finalize` hook is never called for that resource.

**Comment by srfrnk** [comment]
Interestingly enough if I change the response from the `customize` hook to:
```json
{"relatedResources":[{"apiVersion":"jabos.io/v1","resource":"git-repositories","names":["first-repo"]}]}
```
(i.e. no `namespace` specified.)

This issue will not happen.
Perhaps this should be documented... but I think it still should be considered a bug.

**Comment by srfrnk** [comment]
Update: the fix above removes the Warning Event however I start getting `related` resources from other namespaces in my `sync` hook. I now have to filter these so that I do not use the wrong related resource. This I think definitely constitutes a bug if not even a **security risk**.

**Comment by grzesuav** [comment]
hi @srfrnk , I think it is related to https://metacontroller.github.io/metacontroller/guide/best-practices.html#objects-relationship constrains on related resources - if parent resource is namespaced, `related` resources can be (currently, because there is https://github.com/metacontroller/metacontroller/issues/345) from the same namespace as parent.

**Comment by srfrnk** [comment]
In my case both `parent` and `related` resources are namespaced.
I would expect it to behave as you describe.
However the behavior i'm seeing is the different. The `sync` hook is being called with `related` resources from a **different** namespace.
I had to create a workaround in my code to solve that - it's pretty ugly though... see [here](https://github.com/srfrnk/jabos/blob/ca2ec1c42bded5464be91af27034adea9d352da1/operator/misc.ts#L45)

**Comment by grzesuav** [comment]
hmm @srfrnk , so when processing  
```yaml
---
apiVersion: jabos.io/v1
kind: JsonnetManifest
metadata:
  name: simple-jsonnet-manifest
  namespace: example-env
spec:
  gitRepository: first-repo
  path: simple-runtime/manifests
  targetNamespace: example-env
  commitTLAKey: latestCommitId
``` 
`customize` hook returns 
```
{"relatedResources":[{"apiVersion":"jabos.io/v1","resource":"git-repositories","namespace":"example-env","names":["first-repo"]}]}
```
?
What do you see in logs (they are more explicit)

**Comment by srfrnk** [comment]
@grzesuav - I've created a small repo to show what's going on...
If you clone [this commit](https://github.com/srfrnk/metacontroller-playfield/commit/e8fce2d5d9bfe6fd47d7e0ab2c333d63de8fbe39) you can run and see how it behaves.
In short once the `make deploy-tests` is run you start getting the following logs from the `metacontroller` container:
```json
{"level":"error","ts":1641896496.810089,"msg":"failed to sync test-controller 'test.io/v1:Test:test2:test1': requested related object namespace test1 differs from parent object namespace test2\n","stacktrace":"metacontroller/pkg/controller/decorator.(*decoratorController).worker\n\t/go/src/metacontroller/pkg/controller/decorator/controller.go:294\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.22.4/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.22.4/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.22.4/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.22.4/pkg/util/wait/wait.go:90\nmetacontroller/pkg/controller/decorator.(*decoratorController).Start.func1.1\n\t/go/src/metacontroller/pkg/controller/decorator/controller.go:268"}
```

Notice the configuration being deployed:
```yaml
apiVersion: test.io/v1
kind: Test
metadata:
  name: test1
  namespace: test1
spec:
  prop: "related1"
---
apiVersion: test.io/v1
kind: Test
metadata:
  name: test1
  namespace: test2
spec:
  prop: "related1"
```

While operator logs show:
```
test customize res {"relatedResources":[{"apiVersion":"test.io/v1","resource":"relatedes","namespace":"test2","names":["related1"]}]}
```
and 
```
test customize res {"relatedResources":[{"apiVersion":"test.io/v1","resource":"relatedes","namespace":"test1","names":["related1"]}]}
```

**Comment by srfrnk** [comment]
Any thought on that?

I think I found one problem [here](https://github.com/metacontroller/metacontroller/blob/c7cc1891b24ae15e75e348a760e3097f2af9b976/pkg/controller/common/customize/manager.go#L384) - if `relatedRule.Namespace` is empty I think it will be returning resources from **all** namespaces. If these share the same `name` only the last one will be attached (might be from a different namespace) which is what I'm seeing in my code right now. I think the documentation suggests in this case `parentNamespace` should be used - Am I wrong?

I created a PR - maybe that would do it? https://github.com/metacontroller/metacontroller/pull/419

**Comment by grzesuav** [comment]
@srfrnk why you do not set correct `Namespace` in `customize` hook response ? For me it would be the correct behavior and would fix your case

**Comment by grzesuav** [comment]
Looking at the code, the `Namespace` should be taken from `relatedRule. Namespace`, which should be set by your `customize` hook. Are you sure it is there ?

**Comment by srfrnk** [comment]
The reason for the `relatedRule.Namespace` to be missing from `customize` hook response is [to workaround this](https://github.com/metacontroller/metacontroller/issues/414#issuecomment-1009826183)
Furthermore [documentation](https://metacontroller.github.io/metacontroller/api/customize.html#customize-hook) says:
> namespace | Optional. The Namespace to select in

and:
> Specifying the namespace is optional, but if specified must match.

This I assume not returning the `namespace` should be supported. Is that not what it means?

**Comment by grzesuav** [comment]
> > namespace | Optional. The Namespace to select in
> 
> and:
> 
> > Specifying the namespace is optional, but if specified must match.
> 
> This I assume not returning the `namespace` should be supported. Is that not what it means?
yep, it means that putting `Namespace` there isn't obligatory, you can omit it - then objects from all namespaces matching the name will be returned.

**Comment by srfrnk** [comment]
So if the parent is namespaced and I don't specify a namespace I would get related resources from other namespaces? I'd that the intended behaviour? I would  think it goes against the the concept of namespaces don't you agree?

**Comment by grzesuav** [comment]
There is a FR for multi-namespace support - https://github.com/metacontroller/metacontroller/issues/345 - so I am bit oppose of introducing defaulting mechanism.   

I still do not understand why the original problem exists, will look at your example over the week, asking questions here if necessary.

Will try to add `example` controller if necessary .

**Comment by srfrnk** [comment]
Multi-namespace support would be awesome.
Not sending the namespace in the customize response was a workaround - so I'd obviously prefer to not use it...
My guess is the problem originates from using the same name in two namespaces.
When filtering the code uses the name for the key in the dictionary - thus another resource with the same name but a different namespace would overwrite the resource with the same name from the parent's namespace - resulting in the sync trying to provide an object with a related resource of a different namespace - hence he error `Warning  SyncError  2s (x11 over 7s)  metacontroller  Sync error: requested related object namespace stg differs from parent object namespace example-env`.
Does that make sense?

**Comment by srfrnk** [comment]
I has another look into it.
I actually think the original problem wasn't with the related objects being used from a different namespace.
I think it has to do with caching the `customize` response which **only uses the parent name** thus two resources with the same name bug different namespaces would overwrite the cache - then only the last of these will be used in the `sync` `GetRelatedObjects` function - resulting in one of them "trying" to get a related object from a different namespace.

I removed the workaround.

I updated the PR... but my Go is not really good maybe I chose the wrong way to do it? WDYT?

**Comment by splitice** [comment]
I've been reading into this issue and I must say I've gotten myself fairly confused. That said I looked through the code and the design documents and I can't see any reason that at-least simple cluster level resources couldnt be provided as related resources.

This would enable configs like:
```
apiVersion: metacontroller.k8s.io/v1alpha1
kind: DecoratorController
metadata:
  name: dnsname-per-node
spec:
  resources:
  - apiVersion: v1
    resource: pods
   [...]
  attachments:
  - apiVersion: v1
    resource: services
  hooks:
    customize: [...]
```

Where customize returns: 
```
  'relatedResources': [
    {
      'apiVersion': 'v1',
      'resource': 'nodes'
    },
  ]
```

This enables the providing of node objects to the pods of daemonsets...
