### ISSUE TITLE
Using downwardApi without apiVersion leads to never-ending pod delete/recreate loop

### ISSUE THREAD

**Issue by gavin-nia** [metacontroller/metacontroller#443]
metacontroller version 2.2.0

Using the downwardAPI in a pod spec seems to lead to a never ending cycle of destroying/recreating the pod. Example:

```
downwardAPI:
 items:
   - path: pod_name
     fieldRef:
       fieldPath: metadata.name
```

A workaround is to add apiVersion: v1 under the fieldRef from our side.
