### ISSUE TITLE
Adopting existing resources using label selector does not seem to work

### ISSUE THREAD

**Issue by rolandkool** [metacontroller/metacontroller#573]
I have trouble getting this feature to work: https://metacontroller.github.io/metacontroller/api/compositecontroller.html#label-selector

Trying to have my controller adopt existing resources based on labels I provide through the custom resource. However, metacontroller keeps logging the following error:
> .spec.selector must have either matchLabels, matchExpressions, or both

This is from this code: https://github.com/metacontroller/metacontroller/blob/master/pkg/controller/composite/controller.go#L632

The CRD contains the following schema:
```
   schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              selector:
                description: 'Selector'
                type: object
              otherParameter:
                description: 'Some other parameter'
                type: array
                items:
                  type: string
            required:
            - selector
          status:
            type: object
            properties:
              working:
                type: string
        required:
        - spec
```

A custom resource example looks like this:
```
---
apiVersion: infra.poc.example.com/v1
kind: TestResource
metadata:
  name: test
spec:
  selector:
    matchLabels:
      application-name: test
```

When I make the selector optional in the CRD and remove the selector from the custom resource, I still the same error, although I would expect to get the error from https://github.com/metacontroller/metacontroller/blob/master/pkg/controller/composite/controller.go#L627

I can workaround this by still using the `generateSelector` and patching the child objects to have the `controller-uid` label.

**Comment by grzesuav** [comment]
@rolandkool I think that the schema can be an issue, 
```yaml
                    labelSelector:
                      description: A label selector is a label query over a set of
                        resources. The result of matchLabels and matchExpressions
                        are ANDed. An empty label selector matches all objects. A
                        null label selector matches no objects.
                      properties:
                        matchExpressions:
                          description: matchExpressions is a list of label selector
                            requirements. The requirements are ANDed.
                          items:
                            description: A label selector requirement is a selector
                              that contains values, a key, and an operator that relates
                              the key and values.
                            properties:
                              key:
                                description: key is the label key that the selector
                                  applies to.
                                type: string
                              operator:
                                description: operator represents a key's relationship
                                  to a set of values. Valid operators are In, NotIn,
                                  Exists and DoesNotExist.
                                type: string
                              values:
                                description: values is an array of string values.
                                  If the operator is In or NotIn, the values array
                                  must be non-empty. If the operator is Exists or
                                  DoesNotExist, the values array must be empty. This
                                  array is replaced during a strategic merge patch.
                                items:
                                  type: string
                                type: array
                            required:
                            - key
                            - operator
                            type: object
                          type: array
                        matchLabels:
                          additionalProperties:
                            type: string
                          description: matchLabels is a map of {key,value} pairs.
                            A single {key,value} in the matchLabels map is equivalent
                            to an element of matchExpressions, whose key field is
                            "key", the operator is "In", and the values array contains
                            only "value". The requirements are ANDed.
                          type: object
                      type: object
```
look at https://github.com/metacontroller/metacontroller/blob/master/manifests/production/metacontroller-crds-v1.yaml#L585

**Comment by rolandkool** [comment]
I'm using a CompositeController and not a DecoratorController. Looks like this part of the schema only applies to a DecoratorController.

**Comment by grzesuav** [comment]
@rolandkool it was just example how label selector field should be specified in schema

**Comment by grzesuav** [comment]
so no 
```yaml
              selector:
                description: 'Selector'
                type: object
```
but the part I copied above
