### ISSUE TITLE
Log wrong webhook url error.

### ISSUE THREAD

**Issue by timdevlet** [metacontroller/metacontroller#587]
Hello. I need to count all errors with Prometheus. Imagine you have a domain in CompositeController.

 ```
   hooks:
      sync:
        webhook:
          etag:
            enabled: true
          url: https://domain.com/sync?foo=bar
    parentResource:

```

If you have the wrong parameter https://domain.com/**sinc** (sinc VS sync) this query can log this:

`sum by (cluster, domain, code, instance) (rate   (metacontroller_sync_requests_total {cluster=~"$Cluster", domain=~"$Domain", instance=~"$Instance", **code**!="200"}[10m] )  ) > 0`

But if you have an error in the domain name ( wrongdomain.com VS domain.com), the error doesn't store in the metacontroller_sync_requests_total.

I can't catch this behavior (invalid domain name in webhook) and track it down.

in my opinion we need a simple mechanism to count all errors that we see in the logs.
