### ISSUE TITLE
What is the recommended upgrade procedure? Or: possible bug, "apiVersion" is not checked in "parentResource" of CompositeController

### ISSUE THREAD

**Issue by EmielBruijntjes** [metacontroller/metacontroller#695]
Is there documentation about the recommended procedure for (slowly) rolling out changes to webhooks?

For example, when we make changes to a webhook script, we rather not have such changes automatically applied when the periodic sync-process runs. So instead of making changes to a webhook, we prefer to add a *new* webhook, and use that for selected resources. This allows us to better keep an eye on possible errors. I tried to achieve this by setting up multiple webhook endpoints, one that is known to work, and a "beta" one we use for new code:
```
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: example-v1
spec:
  parentResource:
    apiVersion: example.com/v1
    resource: examples
  childResources: ...
  hooks:
    sync:
      webhook:
        url: http://webhook.metacontroller/examples/v1
---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: example-v2alpha1
spec:
  parentResource:
    apiVersion: example.com/v2alpha1
    resource: examples
  childResources: ...
  hooks:
    sync:
      webhook:
        url: http://webhook.metacontroller/examples/v2alpha1
```
In the associated CRD we can then add a "v1" and a "v2alpha1" version. I thought that this would be a nice way to slowly rollout a new version. The "v2alpha1" endpoint will only be called for clients that explicitly use "example.com/v2alpha1".

However, when we create a "Kind: Example" resource, with apiVersion set to "example.com/v1", **both** of the above endpoints are called. This surprised me. Is this a bug in MetaController (that "parentResource.apiVersion" is not checked) or is my understanding of this process wrong, and is there an alternative process for rolling out changes to the webhook?
