### ISSUE TITLE
CompositeController resource not found

### ISSUE THREAD

**Issue by andre-lx** [metacontroller/metacontroller#714]
Hello. 

We are using metacontroller from quite a while in our environment without any problems, but since last week we are getting an error that we cannot understand at all. 

It's also working in our older clusters. This fails only for new deployments.

The following composite controller can be used as an example:

```yaml
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: composite-test
spec:
  generateSelector: true
  resyncPeriodSeconds: 30
  parentResource:
    apiVersion: v1
    resource: namespaces
    #apiVersion: apps/v1
    #resource: deployments
childResources:
  - apiVersion: v1
    resource: secrets
    updateStrategy:
      method: OnDelete
  hooks:
    sync:
      webhook:
        url: http://..../sync
```

Setting the parent resource as any resource type we always get:

`
{"level":"error","ts":1668512520.689139,"msg":"Reconciler error","controller":"composite-metacontroller","object":{"name":"composite-test"},"namespace":"","name":"composite-test","reconcileID":"e879d389-eab3-4dd1-abfc-fa389e411ab2","error":"CustomResourceDefinition.apiextensions.k8s.io \"namespaces.\" not found","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:326\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:234"}
`

deployments:
`
 \"deployments.apps\" not found"
`

We already tried the last version, and also in a new empty cluster.

We also tried the example provided in the docs, with the same error message. It looks different from the troubleshooting in the docs: https://metacontroller.github.io/metacontroller/guide/troubleshooting.html#common-log-messages

Kubernetes version: 1.22 and 1.23
Metacontroller version: v4.5.7

Is this something on our end? 

Thanks

**Comment by hhk7734** [comment]
```yaml
spec:
  parentResource:
    apiVersion: v1
    resource: namespaces
```

I use Namesapce for parentResource. Namespace is in core/v1, but metacontroller seems to find it in CustomResourceDefinition.

**Comment by grzesuav** [comment]
@hhk7734 composite controller is for working with your own types, if you want to have kubernetes API type as parent use decorator controller

**Comment by grzesuav** [comment]
@andre-lx :arrow_up:

**Comment by hhk7734** [comment]
I changed CompositeController to DecoratorController and it works fine. Thanks :+1: 

```yaml
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  # ...
spec:
  parentResource:
    apiVersion: v1
    resource: namespaces
  childResources:
    # ...
```

```yaml
apiVersion: metacontroller.k8s.io/v1alpha1
kind: DecoratorController
metadata:
  # ...
spec:
  resources:
    - apiVersion: v1
      resource: namespaces
  attachments:
    # ...
