### ISSUE TITLE
yaml in, yaml out? 

### ISSUE THREAD

**Issue by ns-rlewkowicz** [metacontroller/metacontroller#781]
So I have a simple decorator controller with a simple sync hook. Now I haven't messed with this in a while, but I swear you can do more than just attachments. 

The goal is take a pod, and force resource limits. 

```
---
apiVersion: v1
data:
  sync.py: |-
    from typing import Optional
    import logging
    import typing
    import json
    import copy
    from pprint import pformat

    from fastapi import FastAPI, Request
    from fastapi.encoders import jsonable_encoder
    from fastapi.responses import JSONResponse


    logging.basicConfig(level=logging.DEBUG)
    LOGGER = logging.getLogger(__name__)
    LOGGER.info("started")

    app = FastAPI()

    @app.api_route("/{anything:path}", methods=["GET", "POST"])
    async def catch_all(anything: str, request: Request):
        body = await request.json()
        pod = body['object']
        LOGGER.info({"Method": request.method,
                "URL": request.url,
                "Headers": dict(request.headers.items()),
                "Query Parameters": dict(request.query_params.items()),
                "Path Parameters": request.path_params,
                "Client": request.client.host})
        for i in range(0, len(body['object']['spec']['containers'])):
          LOGGER.info(json.dumps(body['object']['spec']['containers'][i]['resources']))
          pod['spec']['containers'][i]['resources'] = {'limits': {'cpu': '10m', 'memory': '10Mi'}, 'requests': {'cpu': '10m', 'memory': '10Mi'}} 
        LOGGER.info(json.dumps(pod))
        json_compatible_item_data = jsonable_encoder(pod)
        return JSONResponse(content=json_compatible_item_data)
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: resource-setter
  namespace: metacontroller
---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: DecoratorController
metadata:
  name: resource-setter
spec:
  resources:
  - apiVersion: v1
    resource: pods
    labelSelector:
      matchLabels:
        meta: test
  hooks:
    sync:
      webhook:
        url: http://resource-setter.metacontroller/sync-resource-setter
        timeout: 10s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-setter
  namespace: metacontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-setter
  template:
    metadata:
      labels:
        app: resource-setter
    spec:
      containers:
      - name: controller
        image: "tiangolo/uvicorn-gunicorn-fastapi:latest"
        workingDir: /hooks
        command: ["uvicorn", "sync:app", "--reload", "--port", "80", "--host", "0.0.0.0", "--log-level", "trace"]
        volumeMounts:
        - name: hooks
          mountPath: /hooks
      volumes:
      - name: hooks
        configMap:
          name: resource-setter
---
apiVersion: v1
kind: Service
metadata:
  name: resource-setter
  namespace: metacontroller
spec:
  selector:
    app: resource-setter
  ports:
  - port: 80
    targetPort: 80
```

The Nginx pod:

```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    meta: test
    run: nginx
  name: nginx
  namespace: metacontroller
spec:
  containers:
  - image: nginx
    name: nginx
    resources:
      requests:
        memory: "100Mi"
        cpu: "100m"
      limits:
        memory: "100Mi"
        cpu: "100m"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
```

Now metacontroller sees it, but does not recreate the returned pod object. Is this not a use case?
