### ISSUE TITLE
Panic when only using the finalize hook in decorator

### ISSUE THREAD

**Issue by Shashankft9** [metacontroller/metacontroller#948]
I have a usecase where i want to a hook to be called only when the resource is being deleted, with the assumption that nothing has to be done for create/update operations.

So, if i mention only the finalize hook, I see a runtime panic error in the logs of metacontroller:

![image](https://github.com/metacontroller/metacontroller/assets/48708039/00d1750c-e424-4caa-b99e-0fea5353ffda)

Decorator looks something like this:
```
apiVersion: metacontroller.k8s.io/v1alpha1
kind: DecoratorController
metadata:
  name: call-removal-api
spec:
  hooks:
    finalize:
      version: v1
      webhook:
        url: http://call-removal-api.metacontroller.svc.cluster.local?type=delete    
  resources:
  - apiVersion: helm.toolkit.fluxcd.io/v2beta1
    resource: helmreleases
```
Should this be a supported use case in metacontroller?
