### ISSUE TITLE
Feature request: Disable webhook calls for changes in status of parent CR

### ISSUE THREAD

**Issue by Shashankft9** [metacontroller/metacontroller#986]
We have some CRDs built on top of cluster API that keep on getting updated by their controllers every minute, one such example is a cluster CRD, which we keep on updating every minute to show the health in status. Now using metacontroller, we run some webhooks through decorator where this CRD is the parent, and because its status keeps on getting updated every minute, the webhook is also called along with it, eventually causing too much unnecessary traffic in between.

This could be avoided if somehow we can block metacontroller to call the webhook on status change, but this should not be the default behavior, it should be opted for, maybe through the decorator CR? 
More context here: https://kubernetes.slack.com/archives/CA0SUPUDP/p1715069539278159

If this makes sense and if it is to be considered for a feature, I can help with it!

cc @grzesuav 

- [x] enable this feature at parent resources for composite controller and decorator controller
- [ ] fix update enqueue for parent resources that are being deleted if this feature is enabled
- [ ] enable this feature for attachement/child resources

**Comment by grzesuav** [comment]
To summarize - it is decorator controller and one of the `resources` (https://metacontroller.github.io/metacontroller/api/decoratorcontroller.html#resources) have frequent status update ? 


Some ideas to consider:
1. Extend api,i.e.
```yaml
apiVersion: metacontroller.k8s.io/v1alpha1
kind: DecoratorController
metadata:
  name: service-per-pod
spec:
  resources:
  - apiVersion: apps/v1
    resource: statefulsets
    **ignoreStatusUpdate: true**
  attachments:
  - apiVersion: v1
    resource: services
  hooks:
    sync:
      webhook:
        url: http://service-per-pod.metacontroller/sync-service-per-pod
        timeout: 10s

```
(actually would make sense to add it also to `attachements` and composite controller also), however it would need to be filtered **before** sending `sync`/`finalize` request - need to think if it is doable

2.Add more generic concept similar to https://metacontroller.github.io/metacontroller/api/controllerrevision.html#parent-patch, so expose a field pointing to part of the object controller is interested about - however it can be not easy to implement - the previous value of the part of object under that path would need to be cached somewhere. Need to think a bit on this.

```yaml
apiVersion: metacontroller.k8s.io/v1alpha1
kind: DecoratorController
metadata:
  name: service-per-pod
spec:
  resources:
  - apiVersion: apps/v1
    resource: statefulsets
    **path: spec**
  attachments:
  - apiVersion: v1
    resource: services
  hooks:
    sync:
      webhook:
        url: http://service-per-pod.metacontroller/sync-service-per-pod
        timeout: 10s

```
